### ISSUE TITLE
[Feat] 홈 젤리 봉지 오픈 전 뷰 작업

### ISSUE THREAD

**Issue by wonniiii** [Keyneez/Keyneez-iOS-Release#1]
## 🛠 Issue
<img width="223" alt="스크린샷 2023-05-25 오후 6 09 56" src="https://github.com/Keyneez/Keyneez-iOS-Release/assets/81157265/e76df8f4-5457-44fb-97b4-c5d9ea34132b">

## 📝 To-do
- [x] gif 테스트로 넣고 작업
- [x] gif 라이브러리 찾기
- [x] 최근에 본 활동 collectionView
- [x] 탭바 만들기
- [x] 나머지 UI 짜기
