### ISSUE TITLE
[Feat] 카드 서버 통신 작업

### ISSUE THREAD

**Issue by wonniiii** [Keyneez/Keyneez-iOS-Release#21]
## 🛠 Issue
카드에 관한 정보들을 서버에서 받아옵니다.

## 📝 To-do
- [x] DTO 작성
- [x] ExploreCardViewCell 서버 받아오기
- [x] CardItem, CardViewModel 작업
- [x] RecommendCardViewCell 서버 받아오기
- [x] HomeCardViewCell 서버 받아오기
- [x] 좋아요 POST
