### ISSUE TITLE
[Fix] 서버 통신 에러 수정

### ISSUE THREAD

**Issue by wonniiii** [Keyneez/Keyneez-iOS-Release#24]
## 🛠 Issue
- 서버 통신 작업 중 미완성 부분 해결

## 📝 To-do
- [ ] 이번주 추천활동 좋아요 기능 해결
- [ ] LikedCardCell 좋아요 기능 해결
- [ ] HomeCardCell, ExploreCardCell 좋아요 이미지 업데이트 해결
- [ ] LikeEditView 좋아요 취소 기능 해결
