### ISSUE TITLE
[Fix] UI 수정

### ISSUE THREAD

**Issue by wonniiii** [Keyneez/Keyneez-iOS-Release#25]
## 🛠 Issue
- QA 할만한 UI 요소들 수정합니다.

## 📝 To-do
- [ ] 홈화면 이번 주 기준으로 젤리뷰랑 테이블 뜨는거 해결
- [ ] 카드 셀 레이아웃 변경
- [ ] 모든 뷰 레이아웃 확인
- [ ] 팁 킷 한번만 나오면 다신 안나오게
- [ ] 팁 킷 레이아웃 조정
- [ ] 이번 주 추천활동 카드 셀들 터치 되면 안없어지게
- [ ] 이번 주 추천활동 카드 셀 밑에 selected 인덱스 정확하게
- [ ] 홈화면 스크롤 안되게
- [ ] 탐색하기 검색하다가 탐색하기 뷰 disappear 되면 dismiss되게
