### ISSUE TITLE
[Feat] 로그아웃 및 탈퇴 구현

### ISSUE THREAD

**Issue by kpk0616** [Keyneez/Keyneez-iOS-Release#26]
## 🛠 Issue

- Apple 로그아웃 및 탈퇴 구현
- 카카오 로그아웃, 탈퇴 서버통신 DecodeError 해결

## 📝 To-do

- [x] Apple 로그아웃 및 탈퇴
- [x] 카카오 로그아웃, 탈퇴 서버통신 DecodeError 해결
- [ ] 좋아요 상세뷰 연결
- [x] 설정뷰에서 푸쉬알림 없애기
